project:
    name: blank-app
    app_id: f864e621-f57a-4b63-8b3a-686404f6930e
build:
    system: Expo
    platforms:
        ios:
            commands:
                - npm install
                - npx expo prebuild --platform ios --clean --no-install
                - cd ios && pod install
                - cd ios && xcodebuild -workspace BlankApp.xcworkspace -scheme BlankApp -configuration Debug -sdk iphonesimulator -destination 'generic/platform=iOS Simulator' -derivedDataPath build ARCHS=arm64 CODE_SIGNING_ALLOWED=NO
            output: ios/build/Build/Products/Debug-iphonesimulator/BlankApp.app
            app_id: f864e621-f57a-4b63-8b3a-686404f6930e
defaults:
    open_browser: true
    timeout: 3600
hotreload:
    default: expo
    providers:
        expo:
            port: 8081
            app_scheme: blank-app
            platform_keys:
                ios: ios
